name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - pillow
  - pandas
  - pyyaml
  - seaborn
  - requests
  - scipy
  - openssl
  - tensorflow-cpu
  - keras
  - h5py
  - opencv
  - tqdm
  - scikit-image
  - scikit-learn
