name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - matplotlib>=3.2.2
  - pillow>=7.1.2
  - pandas>=1.1.4
  - pyyaml>=5.3.1
  - seaborn>=0.11.0
  - requests>=2.23.0
  - scipy==1.10.1
  - openssl==1.1.1l
  - tensorflow-cpu==2.7.0
  - keras==2.7.0
  - h5py==3.10.0
  - opencv-python==4.9.0.80
  - tqdm==4.66.1
  - scikit-image==0.21.0
  - scikit-learn==1.3.2
